using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace MeetingScribe.Logic.Meeting;

public partial class MeetingSession : ObservableObject
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string FolderPath { get; set; } = "";


    public string Language { get; set; } = "en";
    [ObservableProperty] private string _name = string.Empty;
    [ObservableProperty] private string _description = string.Empty;
    [ObservableProperty] private string _meetingTopics = string.Empty;


    public DateTime StartTime { get; set; } = DateTime.Now;
    public TimeSpan Duration { get; set; }


    public ObservableCollection<TranscriptLine> FullTranscript { get; set; } = new();   // Full transcription
    [ObservableProperty]
    private ObservableCollection<Participant> _participants = new();  // All participants who take part in meeting

    // Two types of Summaries for the meeting and the flag indicating whether the summary has been generated or not
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowSummaryTabs))]
    private string? _generalSummary;
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowSummaryTabs))]
    private string? _templateSummary;

    public bool hasSummary => !string.IsNullOrEmpty(GeneralSummary);
    public bool HasTemplateSummary => !string.IsNullOrWhiteSpace(TemplateSummary);
    public bool ShowSummaryTabs => !string.IsNullOrWhiteSpace(GeneralSummary) &&
                                   !string.IsNullOrWhiteSpace(TemplateSummary);

    public bool hasTranscription => FullTranscript.Count > 0;
    [ObservableProperty] private bool _hasImprovedRecognition; // After AI processing, if the recognition has been improved
    [ObservableProperty] private bool _hasAIImprovements;      // After AI processing, if there are any improvements suggested by the AI
    [ObservableProperty] private bool _hasSummary;             // After AI processing, if there is a summary generated by the AI

    //  List of interim small summaries on text chunks
    public List<string> SegmentSummaries { get; set; } = new();
}