<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Remove="Assets\Denoise\deep-filter-0.5.6-x86_64-pc-windows-msvc.exe" />
    <AvaloniaResource Remove="Assets\Denoise\deep-filter.exe" />
    <AvaloniaResource Remove="Assets\I18n\en.json" />
    <AvaloniaResource Remove="Assets\I18n\it.json" />
    <AvaloniaResource Remove="Assets\Manifests\ai_providers.json" />
    <AvaloniaResource Remove="Assets\Manifests\languages_manifest.json" />
    <AvaloniaResource Remove="Assets\Manifests\models_manifest.json" />
    <AvaloniaResource Remove="Assets\Manifests\Venue.json" />
    <AvaloniaResource Remove="Assets\Models\silero_vad.onnx" />
    <AvaloniaResource Remove="Assets\Template\VerbaleRiunione_Gen.docx" />
    <AvaloniaResource Remove="Assets\Template\VerbaleRiunione_Template.docx" />
    <AvaloniaResource Remove="Assets\WhisperModels\ggml-base.bin" />
    <AvaloniaResource Remove="Assets\WhisperModels\ggml-large-v3-turbo-q8_0.bin" />
    <AvaloniaResource Remove="Assets\WhisperModels\ggml-large-v3-turbo.bin" />
    <AvaloniaResource Remove="Assets\WhisperModels\ggml-medium.bin" />
    <AvaloniaResource Remove="Assets\WhisperModels\ggml-small.bin" />
    <Folder Include="Styles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="DocX" Version="5.2.0" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Markdown.Avalonia.Tight" Version="12.0.0-a2" />
    <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.1" />
    <PackageReference Include="Mscc.GenerativeAI" Version="3.1.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="ThingLing.Avalonia.Controls.MessageBox" Version="2.0.0" />
    <PackageReference Include="Whisper.net" Version="1.9.1" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Denoise\deep-filter.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Denoise\deep-filter-0.5.6-x86_64-pc-windows-msvc.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\I18n\en.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\I18n\it.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Manifests\Venue.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Template\VerbaleRiunione_Gen.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Template\VerbaleRiunione_Template.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Windows\AddGroupWindow.axaml.cs">
      <DependentUpon>AddGroupWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Manifests\ai_providers.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Manifests\languages_manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Manifests\models_manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Models\silero_vad.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="secrets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WhisperModels\ggml-base.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WhisperModels\ggml-large-v3-turbo-q8_0.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WhisperModels\ggml-large-v3-turbo.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WhisperModels\ggml-medium.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\WhisperModels\ggml-small.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
